spring.application.name=notification-service

# WHY: Notification service runs on 8084
server.port=8084

# WHY: Same MongoDB database
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=eventbooking_db
spring.data.mongodb.auto-index-creation=false

# WHY: Tells Spring where Kafka is running
spring.kafka.bootstrap-servers=localhost:9092

# WHY: Consumer group ID
# All notification service instances share this group
# Ensures each message processed only once
spring.kafka.consumer.group-id=notification-group

# WHY: How to deserialize incoming messages
# StringDeserializer converts bytes back to String
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# WHY: What to do when consumer joins for first time
# earliest = read all messages from beginning
# latest = read only new messages
spring.kafka.consumer.auto-offset-reset=earliest

logging.level.com.eventbooking=DEBUG