spring.application.name=bookingservice
server.port=8083

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=eventbooking_db

spring.data.mongodb.auto-index-creation=false
logging.level.com.eventbooking=DEBUG

# WHY: Secret key used to sign JWT tokens
# Must be at least 256 bits (32 characters) for HS256 algorithm
# Keep this secret - never push to GitHub
jwt.secret=eventbooking2026secretkeyforjwttokengenerationandsigning

# WHY: How long token is valid
# 86400000 milliseconds = 24 hours
# After this time user must login again
jwt.expiration=86400000

# WHY: Tells Spring Boot where Kafka broker is running
spring.kafka.bootstrap-servers=localhost:9092

# WHY: How to convert our message to bytes
# StringSerializer converts String to bytes for sending
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer