spring.application.name=user-service
server.port=8081
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=eventbooking_db
spring.data.mongodb.auto-index-creation=false
logging.level.com.eventbooking=DEBUG
# WHY: Secret key used to sign JWT tokens
# Must be at least 256 bits (32 characters) for HS256 algorithm
# Keep this secret - never push to GitHub
jwt.secret=eventbooking2026secretkeyforjwttokengenerationandsigning

# WHY: How long token is valid
# 86400000 milliseconds = 24 hours
# After this time user must login again
jwt.expiration=86400000