#spring.application.name=event-service
#server.port=${SERVER_PORT:8082}
#spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/eventbooking_db}
#
#spring.data.mongodb.auto-index-creation=false
#
#logging.level.com.eventbooking=DEBUG
spring.application.name=event-service
server.port=8082
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=eventbooking_db
spring.data.mongodb.auto-index-creation=false
logging.level.com.eventbooking=DEBUG
# WHY: Secret key used to sign JWT tokens
# Must be at least 256 bits (32 characters) for HS256 algorithm
# Keep this secret - never push to GitHub
jwt.secret=eventbooking2026secretkeyforjwttokengenerationandsigning

# WHY: How long token is valid
# 86400000 milliseconds = 24 hours
# After this time user must login again
jwt.expiration=86400000

# WHY: Tells Spring where Redis is running
spring.data.redis.host=localhost
spring.data.redis.port=6379

# WHY: How long to keep data in Redis cache
# 600 seconds = 10 minutes
# After 10 minutes cache expires
# Fresh data fetched from MongoDB
spring.cache.redis.time-to-live=600000